# Generated by Django 5.2.10 on 2026-02-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('course', models.CharField(choices=[('python', 'Python'), ('django', 'Django'), ('react', 'React'), ('javescript', 'JavaScript'), ('java', 'Java'), ('c++', 'C++')], max_length=100)),
                ('price', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
